experimental-features = nix-command flakes

# CIのコンテナ環境などrootでNixをsingle-userインストールする際、
# 存在しないnixbldグループを要求されることがあるため、build-users-groupを空にしておく
# multi-user(daemon)環境ではNixデーモン自身が持つ設定が使われるため、この設定は影響しない
# 参考: https://github.com/NixOS/nix/issues/1559
build-users-group =
