name: update
description: Update dotfiles

runs:
  using: "composite"

  steps:
    - name: Update
      shell: bash
      run: |
        set -eu
        touch "${HOME}/.bashrc"

        ./install.sh

        # Nixと、Nix profileでインストールしたコマンド(の内1つ)が存在するか確認する
        bash -c 'source "${HOME}/.bashrc" && type nix'
        bash -c 'source "${HOME}/.bashrc" && type bat'
        # エイリアスが設定できていることを確認する
        bash -c 'source "${HOME}/.bashrc" && alias cat'
