name: update
description: Update dotfiles

runs:
  using: "composite"

  steps:
    - name: Update
      shell: bash
      run: |
        set -eu
        exec bash -l
        ${DOTFILES_DIRECTORY}/install.sh
        exec bash -l
        # Homebrewと、Homebrewでインストールしたコマンド(の内1つ)が存在するか確認する
        type brew
        type bat
        # エイリアスが設定できていることを確認する
        alias cat
