#!/bin/bash

alias ..='cd ..'
alias cd='z'
alias e='exa --long --all --icons --time-style iso --ignore-glob ".git"'
alias et='exa --long --all --icons --time-style iso --sort newest --ignore-glob ".git"'
alias exit='exit 0'
alias icdiff='icdiff -U 1 -N -H'
alias l='ls -AFhg --no-group --color=auto'
alias la='ls -A --color=auto'
alias less='less -NMR'
alias ll='ls -AlF --color=auto'
alias ls='ls -AF --color=auto'
alias open='xdg-open'
alias sl='ls'
alias ssh='ssh -XC'
alias start='xdg-open'
alias view='vim -RM'