name: install
description: Install dotfiles

runs:
  using: "composite"

  steps:
    - name: Install
      shell: bash
      run: |
        set -eu
        ./install.sh
        exec bash -l
        # Homebrewと、Homebrewでインストールしたコマンド(の内1つ)が存在するか確認する
        type brew
        type bat
        # エイリアスが設定できていることを確認する
        alias cat
