name: uninstall
description: Uninstall dotfiles

runs:
  using: "composite"

  steps:
    - name: Uninstall
      shell: bash
      run: |
        set -eu
        exec bash -l
        ${DOTFILES_DIRECTORY}/uninstall.sh
        exec bash -l
        # Homebrewと、Homebrewでインストールしたコマンド(の内1つ)が存在していないこと確認する
        if type brew &>/dev/null; then false; fi
        if type bat &>/dev/null; then false; fi
        # エイリアスが設定されないことを確認する
        if alias cat &>/dev/null; then false; fi
