name: uninstall
description: Uninstall dotfiles

runs:
  using: "composite"

  steps:
    - name: Uninstall
      shell: bash
      run: |
        set -eu
        ./uninstall.sh

        # Nixと、Nix profileでインストールしたコマンド(の内1つ)が存在していないこと確認する
        if bash -c 'source "${HOME}/.bashrc" && type nix' &>/dev/null; then false; fi
        if bash -c 'source "${HOME}/.bashrc" && type bat' &>/dev/null; then false; fi
        # エイリアスが設定されないことを確認する
        if bash -c 'source "${HOME}/.bashrc" && alias cat' &>/dev/null; then false; fi
