name: Format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  shellscript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_comment: true

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: format check
        if: ${{ github.event_name == 'pull_request' }}
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: "true"
          prettier_flags: "**/*.{json,md,yml}"

      - name: Run the prettier
        if: ${{ github.event_name != 'pull_request' }}
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write "**/*.{json,md,yml}"
      - name: Check for changes
        if: ${{ github.event_name != 'pull_request' }}
        run: git diff --exit-code
