name: Install applications

on: [push, pull_request, workflow_dispatch]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          set -e
          bash install.sh
          source ~/.bashrc
