name: Install applications

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 5"

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          set -eu
          ./install.sh
          exec bash -l
          # Homebrewと、Homebrewでインストールしたコマンド(の内1つ)が存在するか確認する
          type brew
          type bat

      - name: Update
        run: |
          set -eu
          exec bash -l
          ${DOTFILES_DIRECTORY}/install.sh
          exec bash -l
          # Homebrewと、Homebrewでインストールしたコマンド(の内1つ)が存在するか確認する
          type brew
          type bat

      - name: Uninstall
        run: |
          set -eu
          exec bash -l
          ${DOTFILES_DIRECTORY}/uninstall.sh
          exec bash -l
          # Homebrewと、Homebrewでインストールしたコマンド(の内1つ)が存在していないこと確認する
          if type brew &>/dev/null; then false; fi
          if type bat &>/dev/null; then false; fi
