name: Install applications

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 5"

jobs:
  install-linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ["rockylinux:9", "ubuntu:latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        run: |
          if [ "${{ matrix.container }}" = "rockylinux:9" ]; then
            dnf groupinstall -y "Development Tools"
            dnf install -y --allowerasing procps-ng curl file git
          elif [ "${{ matrix.container }}" = "ubuntu:latest" ]; then
            apt-get update && apt-get install -y build-essential procps curl file git
          fi

      - name: Install
        uses: ./.github/workflows/install

      - name: Update
        uses: ./.github/workflows/update

      - name: Uninstall
        uses: ./.github/workflows/uninstall

  install-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/install

      - name: Update
        uses: ./.github/workflows/update

      - name: Uninstall
        uses: ./.github/workflows/uninstall
