name: Install applications

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 5"

jobs:
  install-linux:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ["rockylinux:9", "ubuntu:latest"]
    # 未認証のままだとflake.nixのnixpkgs取得時にGitHub APIのレート制限に引っかかることがあるため、認証する
    env:
      NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

    steps:
      - uses: actions/checkout@v6

      - name: Set up
        run: |
          if [ "${{ matrix.container }}" = "rockylinux:9" ]; then
            dnf install -y --allowerasing curl xz git
          elif [ "${{ matrix.container }}" = "ubuntu:latest" ]; then
            apt-get update && apt-get install -y curl xz-utils git
          fi

      - name: Install
        uses: ./.github/workflows/install

      - name: Update
        uses: ./.github/workflows/update

      - name: Uninstall
        uses: ./.github/workflows/uninstall

  install-macos:
    runs-on: macos-latest
    # 未認証のままだとflake.nixのnixpkgs取得時にGitHub APIのレート制限に引っかかることがあるため、認証する
    env:
      NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

    steps:
      - uses: actions/checkout@v6

      - name: Install
        uses: ./.github/workflows/install

      - name: Update
        uses: ./.github/workflows/update

      - name: Uninstall
        uses: ./.github/workflows/uninstall
