name: Install applications

on: [push, pull_request, workflow_dispatch]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: |
          set -e
          ./install.sh
          source ~/.bashrc
          # Homebrewと、Homebrewでインストールしたコマンド(の内1つ)が存在するか確認する
          type brew
          type bat

      - name: Uninstall
        run: |
          set -e
          ./uninstall.sh
          # Homebrewと、Homebrewでインストールしたコマンド(の内1つ)が存在していないこと確認する
          if type brew &>/dev/null; then false; fi
          if type bat &>/dev/null; then false; fi
